"""add cv_content to resume model

Revision ID: 35c0ae97ccfa
Revises: 
Create Date: 2026-04-23 10:34:05.496986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c0ae97ccfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_content', sa.Text(), nullable=True))

    with op.batch_alter_table('recruiter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_company_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiter', schema=None) as batch_op:
        batch_op.drop_column('is_company_admin')
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('cv_content')

    # ### end Alembic commands ###
