"""add top post list

Revision ID: b27c448aebf4
Revises: 3f2518700210
Create Date: 2026-05-06 17:50:28.905916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27c448aebf4'
down_revision = '3f2518700210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('company_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('company_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['city_id'], ['id'])
        batch_op.create_foreign_key(None, 'company_scale', ['scale_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'experience_option', ['experience_id'], ['id'])
        batch_op.create_foreign_key(None, 'salary_option', ['salary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_ibfk_2'), 'experience_option', ['experience_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('post_ibfk_3'), 'salary_option', ['salary_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_ibfk_2'), 'company_scale', ['scale_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('company_ibfk_1'), 'location', ['city_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
