"""Change education and experience to list

Revision ID: f9c799218f76
Revises: 3f2518700210
Create Date: 2026-05-07 15:56:48.631753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9c799218f76'
down_revision = '3f2518700210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('company_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('company_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['city_id'], ['id'])
        batch_op.create_foreign_key(None, 'company_scale', ['scale_id'], ['id'])

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('experience')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'experience_option', ['experience_id'], ['id'])
        batch_op.create_foreign_key(None, 'salary_option', ['salary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_ibfk_2'), 'experience_option', ['experience_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('post_ibfk_3'), 'salary_option', ['salary_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('education', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_ibfk_1'), 'location', ['city_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('company_ibfk_2'), 'company_scale', ['scale_id'], ['id'], ondelete='SET NULL')

    op.drop_table('cv_experience')
    op.drop_table('cv_education')
    # ### end Alembic commands ###
